### ISSUE TITLE
Turning everything into ascii is a bad idea

### ISSUE THREAD

**Issue by fakedrake** [fakedrake/WikipediaBase#20]
The long dash is a very useful unicode character but gdbm seems to accept only ascii. Maybe use another dbm and switch back to unicode.

**Comment by michaelsilver** [comment]
It's easy to get rid of non-ascii in strings using `.encode('ascii', 'ignore')` and then further wrapping in `str()` to get rid of the `u'  '` prefix. I don't know where else non-ascii appears, but in the case of infobox attributes, maybe include an option when retrieving attributes to ignore non-ascii character and convert into clean ascii strings? I was sort of surprised when I first noticed special characters in attributes.

**Comment by michaelsilver** [comment]
By @alvaromorales's suggestion, the [unicode package](https://pypi.python.org/pypi/Unidecode) might do the trick.

**Comment by fakedrake** [comment]
Indeed the unicode package seems nice. For now this is the code that handles unicode -> ascii https://github.com/fakedrake/WikipediaBase/blob/master/wikipediabase/util.py#L271-L273

**Comment by fakedrake** [comment]
I think this is resolved. Unicode goes in, is stored as ascii for caching and goes out as unicode. If there are further bugs regarding this make a new issue that is more specific.
