### ISSUE TITLE
Fix travis tests

### ISSUE THREAD

**Issue by fakedrake** [fakedrake/WikipediaBase#25]
Tests run on my machine make them run on travis too.

**Comment by alvaromorales** [comment]
I ran the tests on an InfoLab machine (Ubuntu 14.04). 40+ tests errored because of the gdbm portability issue. After I deleted tests/data/pages.db the tests passed.

1 test failed an assert: test_simple (tests.test_frontend.TestFrontend)

**Comment by alvaromorales** [comment]
Small addition to my comment above: test_compat_rx (tests.test_resolvers.TestResolvers) also fails. 

```
Traceback (most recent call last):
  File "/afs/csail.mit.edu/u/a/alvarom/chris-pywikipediabase/tests/test_resolvers.py", line 108, in test_compat_rx
    self.assertRegexpMatches(ans, rx, msg=msg)
AssertionError:
	Query: '(get "wikipedia-ocean" "Sea of Azov" (:CODE "DEPTH"))'
	Answer: '((:CODE "39,000Â km2 (15,000Â sqÂ mi)1"))'
	Matcher: '7.*met.*23.*ft'
	Completion: 29\38: '7.*met.*23.*ft' not found in u'((:CODE "39,000\xc2\xa0km2 (15,000\xc2\xa0sq\xc2\xa0mi)1"))'
```

**Comment by fakedrake** [comment]
What you found @alvaromorales is a separate issue. Check #35. XML parsing is also cached in renderer.mdb. Try removing both pages.db and renderer.mdb and see if it persists..

**Comment by alvaromorales** [comment]
Indeed, the error went away after I deleted pages.db and renderer.mdb.

On the bright side, your latest commit solved the tens of gdbm errors, yay. The latest Travis [build](https://travis-ci.org/fakedrake/WikipediaBase/builds/68651412) is only failing test_simple (tests.test_frontend.TestFrontend).

**Comment by fakedrake** [comment]
I have iterated a lot over this and it's driving me mad. The error is contained in `tests/test_frontend.py`. The problem is that the mock function should format using some arguments (line 22) and then the test should check that the right thing was produced (line 34). It works here but I can't get it to work on travis. Can you give it a try @alvaromorales please?

**Comment by alvaromorales** [comment]
It's a Python 2 vs 3 issue. You're calling the repr() function on a unicode object. In Python 2, that prints it with a "u":

```python
>>> article = unicode("article")
>>> repr(article)
"u'article'"
```

The test is failing because the expected string is missing that 'u' from a unicode object. To fix the test, I could change it to look like this:

```python
def test_simple(self):
    self.assertEqual(str(self.simple_fe.eval("(get \"article\" words)")),
                     str("Symbol(words) of u'article'"))
```

... but that would break it in Python 3. I tried using `unicode_str.encode('ascii')`, but in Python 3 that prints with a 'b' prefix. What a mess!

It's awesome that the code is compatible with python 3, but you should probably first test on python 2 since that's what the Infolab machines use.

**Comment by alvaromorales** [comment]
I tested my pull request on python 2 and 3, by the way. Should be good.

On a related note, why are you having to call `repr()`? What is `<class 'edn_format.edn_lex.Symbol'>`?

**Comment by alvaromorales** [comment]
Looks like my pull request fixed the issue, but test_compat_rx (tests.test_resolvers.TestResolvers) is now failing on Travis. Presumably #35?

**Comment by fakedrake** [comment]
I have no idea what is going on with #35... The [merge build](https://travis-ci.org/fakedrake/WikipediaBase/builds/68680713) passes so we're keeping it.
