### ISSUE TITLE
Easy way to install WikiBase?

### ISSUE THREAD

**Issue by michaelsilver** [fakedrake/WikipediaBase#32]
To install WikiBase on malta, I had to do the following:
```Bash
~/WikipediaBase $ sudo pip install -r requirements.txt
~/WikipediaBase $ sudo python setup.py install
~/WikipediaBase $ sudo apt-get install python-gdbm
~/WikipediaBase $ sudo pip install sqlitedict
```
and only then would WikipediaBase work. Could this either be explicitly documented, or alternatively, could there be an automatic install script?

Thanks,

Michael

**Comment by sfelshin** [comment]
"Install", how?  Ruby WikiBase maintains a distinction between the server codebase, which is installed globally (see https://projects.csail.mit.edu/cgi-bin/wiki/view/Infolab/InstallingSourceCode) and the mysql backend, which is separately installed on each machine.  Does Python WikiBase have the same distinction, and if not, how is it organized?

-Sue

**Comment by fakedrake** [comment]
Actually the way that is supposed to work for testers (given that is not production ready that is the only relevant way) is just:

    virtualenv --no-site-packages venv
    . venv/bin/enable
    python setup.py develop # or python setup.py install

If you want a self contained python virtualenv, or if you are willing to use the system wide python installation and are comfortable with using sudo:

    sudo python setup.py install # or develop as above

Could you post the error you get when doing the above? It worked on an fresh linux virtualbox and on a fresh python virtualenv on my mac...

**Comment by fakedrake** [comment]
SOrry I just saw Sue's response: wikipediabase is a python module that comes along with an executable that runs the server, so it can be used either as a python library or as a server from the shell. Whatever database is need (gdbm by default) is created and managed internally when it is needed.

**Comment by michaelsilver** [comment]
Well, when I installed on malta (at the system level, not in a virtualenv for other non-WikipediaBase  reasons), first I did:
```Bash
~/WikipediaBase $ sudo pip install -r requirements.txt
~/WikipediaBase $ sudo python setup.py install
```
Then, although `import wikipediabase` worked in the python shell, when I called some WikipediaBase methods from my script, I got dependency issues.

All I use in my script is:
```Python
>>> from wikipediabase.util import get_infobox, get_meta_infobox
>>> get_meta_infobox('<TEMPLATE_NAME>').rendered_keys()
```
First error:
```Bash
Traceback (most recent call last):
  File "./loadattrmappings.py", line 42, in <module>
    main(sys.argv[1:])
  File "./loadattrmappings.py", line 36, in main
    mappings = get_meta_infobox('Template:Infobox ' + infobox).rendered_keys()
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/util.py", line 77, in get_meta_infobox
    from wikipediabase.infobox_scraper import MetaInfobox
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/infobox_scraper.py", line 7, in <module>
    from wikipediabase.renderer import WIKIBASE_RENDERER
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/renderer.py", line 85, in <module>
    WIKIBASE_RENDERER = SandboxRenderer()
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/renderer.py", line 33, in __init__
    self.cache = util._get_persistent_dict(self.default_file)
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/util.py", line 111, in _get_persistent_dict
    from wikipediabase.persistentkv import PersistentDict
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/persistentkv.py", line 9, in <module>
    import gdbm as dbm
ImportError: No module named gdbm
```
After a quick google search, I installed via `sudo apt-get install python-gdbm`. Rerunning my script, I got yet another dependency error:
```Bash
Traceback (most recent call last):
  File "./loadattrmappings.py", line 42, in <module>
    main(sys.argv[1:])
  File "./loadattrmappings.py", line 36, in main
    mappings = get_meta_infobox('Template:Infobox ' + infobox).rendered_keys()
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/util.py", line 77, in get_meta_infobox
    from wikipediabase.infobox_scraper import MetaInfobox
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/infobox_scraper.py", line 7, in <module>
    from wikipediabase.renderer import WIKIBASE_RENDERER
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/renderer.py", line 85, in <module>
    WIKIBASE_RENDERER = SandboxRenderer()
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/renderer.py", line 33, in __init__
    self.cache = util._get_persistent_dict(self.default_file)
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/util.py", line 111, in _get_persistent_dict
    from wikipediabase.persistentkv import PersistentDict
  File "/usr/local/lib/python2.7/dist-packages/wikipediabase-1.1-py2.7.egg/wikipediabase/persistentkv.py", line 10, in <module>
    from sqlitedict import SqliteDict
ImportError: No module named sqlitedict
```
Then I installed: `sudo pip install sqlitedict`

And only then, finally, could I run my script (using WikipediaBase as a library) with no dependency errors. I suspect you just need to update the `requirements.txt` from your most recent virtualenv.

**Comment by fakedrake** [comment]
are you sure you installed the most recent python wikipediabase? try git
pulling again (make sure it's my repo and not a fork).  I will try it again
myself tonight too.

On an semi related note it is a good idea to use virtualenvs as often as
you can to be able to start from scratch an be more comfortable with
experimenting. you also avoid using sudo on public machines.

**Comment by alvaromorales** [comment]
+1 to using virtualenvs instead of sudo where possible.

**Comment by alvaromorales** [comment]
I had a similar experience to Michael when installing from master. I created pull request #34 that fixes the missing dependency in requirements.txt error and other compile errors.

**Comment by michaelsilver** [comment]
Sorry, I was ready and set up to use a virtualenv, when I came across the problem that I couldn't use the python package MySQLdb, which is actually somewhat of a weird package, because online sources recommend to install it with `sudo apt-get install python-mysqldb` (and there does not appear to be a pip installation). 

(BTW, yes I do know about SQLAlchemy, no need to advertise -- I wanted something simple and quick. I'm having trouble connecting to the mysql backend with MySQLdb, so I might switch anyway.)

**Comment by fakedrake** [comment]
I would recommend [dataset](https://dataset.readthedocs.org/en/latest/) rather than sqlalchemy or MySQLdb for quickies. 

I @michaelsilver just merged @alvaromorales' merge. Could check that it works now please?

**Comment by alvaromorales** [comment]
My merge won't solve the missing gdbm issue (InfoLab machines don't have gdbm installed by default). Should `sudo apt-get install python-gdbm` be added to the installation instructions in the README?

**Comment by fakedrake** [comment]
Yes, I made pull request #38 for that, when @michaelsilver confirms that everything works for him on branch `issue_32` I am merging :)

**Comment by michaelsilver** [comment]
Great, I just tried it and @alvaromorales's merge successfully fixed the dependency issue. What's written in the pull request #37's docs will get one up and running, no problems, so I think we are good and ready to merge and close, @fakedrake. Thanks for helping! :)

**Comment by sfelshin** [comment]
On Jun 27, 2015, at 9:05 PM, Alvaro Morales <notifications@github.com> wrote:
> My merge won't solve the missing gdbm issue (InfoLab machines don't have gdbm installed by default). Should sudo apt-get install python-gdbm be added to the installation instructions in the README?

Should we have gdbm installed by default on Infolab machines?

-Sue

**Comment by fakedrake** [comment]
Although I love gdbm i dont see many other people using it. In my opinion
it's nice to have.

**Comment by alvaromorales** [comment]
Yes, I think that gdbm should eventually be added to the infolabify puppet script (as well as Python tools like pip and virtualenv). But we should hold off until we've thoroughly tested the code and finalized the list of dependencies.

**Comment by michaelsilver** [comment]
> I would recommend dataset rather than sqlalchemy or MySQLdb for quickies. 

@fakedrake `dataset` is working like a charm -- thank you so much for the suggestion!
